package com.kc.poc.drools;
unit TestUnit;

//import function com.kc.poc.drools.util.MathUtil
import com.kc.poc.drools.util.MathUtil;


rule "calculateGrantAmortizationRemainsStartYear"
    when
        $condition : /tests[ vehicule.GrantType != null && vehicule.getGrantPercentage(vehicule.grantType) != null]
        then
        result.add($condition.getVehicule().getContractualNetValueStartYear()
        .multiply($condition.getVehicule().getGrantPercentage($condition.getVehicule().getGrantType())));
        $condition.setGrantAmortizationRemainsStartYear($condition.getVehicule().getContractualNetValueStartYear()
                                                                .multiply($condition.getVehicule().getGrantPercentage($condition.getVehicule().getGrantType())));
        end
query calculAmortissement
    $m: /tests[ vehicule.GrantType != null && vehicule.getGrantPercentage(vehicule.grantType) != null]
    end









