import com.kc.poc.drools.fact.Order;

import com.kc.poc.drools.fact.Customer;

// BRONZE => SILVER
rule "Customer promoted to silver when makes an order over 200"
    when
        $customer : Customer( category == "Bronze")
        orderInstance : Order( customer == $customer , amount >= 300)
    then
        System.out.println("Thank you " + $customer.getName() +  " (before:" + $customer.getCategory() + "), you've made an order over 200, you are now a SILVER customer");
        modify($customer) {
            setCategory("Silver")
        }
end

rule "Customer will receive an email when become silver customer"
    when
        $customer : Customer( category == "Silver")
    then
        System.out.println("EMAIL: Congratulations " + $customer.getName() + ", you are now a silver customer");
end

// SILVER => GOLD
rule "Customer promoted to gold when makes an order over 500 and already silver"
    when
        $customer : Customer( category == "Silver")
        Order( "Silver" == $customer.getCategory() , amount >= 500)
    then
        System.out.println("Thank you " + $customer.getName() +  " (before:" + $customer.getCategory() + "), you've made an order over 500, you are now a GOLD customer");
        modify($customer) {
            setCategory("Gold")
        }
end

rule "Customer will receive an email when become gold customer"
    when
        $customer : Customer( category == "Gold")
    then
        System.out.println("EMAIL: Congratulations " + $customer.getName() + ", you are now a gold customer");
end

query "order amount over 200"
    $order : Order( amount >= 200 )
end