import com.kc.poc.drools.fact.Order;

import com.kc.poc.drools.fact.Customer;

rule "Customer promoted to silver when makes an order over 200 [#1]"
    when
        $customer : Customer( category == "Bronze")
        orderInstance : Order( customer == $customer , amount >= 200)
    then
        System.out.println("[#1]: Thank you " + $customer.getName() +  " (before:" + $customer.getCategory() + "), you've made an order over 200, you are now a silver customer");
//        // modify Category to Silver: Reload the rule file
//        modify($customer) {
//            setCategory("Silver")
//        }
        $customer.setCategory("Silver");
end

rule "Customer promoted to gold when makes an order over 500 [#2]"
    when
        $customer : Customer( category == "Silver")
        orderInstance : Order( customer == $customer , amount >= 500)
    then
        System.out.println("[#2]: Thank you " + $customer.getName() +  " (before:" + $customer.getCategory() + "), you've made an order over 500, you are now a gold customer");
//        modify($customer) {
//            setCategory("Bronze")
//        }
        $customer.setCategory("Gold");
end